server:
  port: 9000
  servlet:
    session:
      timeout: 30m
      cookie:
        name: AUTH_SESSION
        secure: false
        http-only: true
        same-site: lax
        max-age: 3600

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3308/smarty-users?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: 54321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true
      encoding: UTF-8

  # Configuration de la sécurité Spring
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Configuration de Feign Client
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

# Configuration des points de terminaison Actuator pour le monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.app.authservice: DEBUG
    com.app.authservice.client: DEBUG
