server:
  port: 8100
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3308/smarty-users?createDatabaseIfNotExist=true
    username: user
    password: 54321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


# Security
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "*" # Expose tous les endpoints
  endpoint:
    health:
      probes:
        enabled: true
