FROM openjdk:17-jdk-slim

RUN apt-get update && apt-get install -y curl

# répertoire virtuel
WORKDIR /app

COPY target/user-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8100

ENTRYPOINT ["java", "-jar", "app.jar"]
